@startuml

title __RUNNERLIB's Class Diagram__\n

  package com.bupt.colorfulroute {
    package com.bupt.colorfulroute.runningapp.runnerlib {
      class LatLngCalculate {
          {static} - EARTH_RADIUS : double
          {static} - RAD : double
          {static} + getDistance()
          {static} + getPathLength()
          {static} + isSamePoint()
      }
    }
  }
  

  package com.bupt.colorfulroute {
    package com.bupt.colorfulroute.runningapp.runnerlib {
      class RouteGenerate {
          {static} + NORTH : int
          {static} + NORTHEAST : int
          {static} + EAST : int
          {static} + SOUTHEAST : int
          {static} + SOUTH : int
          {static} + SOUTHWEST : int
          {static} + WEST : int
          {static} + NORTHWEST : int
          {static} - getCircleKeyPoints()
          {static} - getCircleKeyPointsByLocation()
          {static} - getRectangleKeyPoints()
          {static} - getFlowerPoints_1()
          {static} - getFlowerPoints_2()
          {static} - getFlowerPoints_3()
          {static} - getFlowerPoints_4()
          {static} - getCircleKeyPointsWithPassingPoint()
          {static} + generateFlowerRoute()
          {static} + generateRoute()
          {static} + generateRouteWithPassingPoint()
      }
    }
  }
  

  package com.bupt.colorfulroute {
    package com.bupt.colorfulroute.runningapp.runnerlib {
      abstract class RunnerRouteSearchListener {
          # resultList : WalkRouteResult[]
          # responseCounter : int
          + RunnerRouteSearchListener()
          + onBusRouteSearched()
          + onDriveRouteSearched()
          + onWalkRouteSearched()
          + onRideRouteSearched()
          {abstract} + successHandler()
          {abstract} + errorHandler()
      }
    }
  }
  

  RunnerRouteSearchListener -up-|> OnRouteSearchListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
